
- name: stop and remove the pod
  ignore_errors: true
  shell: >
    podman pod stop {{ pod_namespace }}

    podman pod rm {{ pod_namespace }}


- name: clean storage
  shell: >
    rm -rf {{ data_root }}/redis
    rm -rf {{ data_root }}/postgres
    rm -rf {{ data_root }}/mastodon
    # keep {{ data_root }}/router to preserve certificates
    # keep {{ config_root }}/router to preserve certificates

