
- name: stop and remove the pod
  ignore_errors: true
  shell: >
    podman pod stop {{ namespace }}

    podman pod rm {{ namespace }}

- name: clean storage
  shell: >
    rm -rf {{ storage_root }}/{{ namespace }}
    # keep {{ data_root }}/router to preserve certificates
    # keep {{ config_root }}/router to preserve certificates

