# syntax=docker/dockerfile:1.4
FROM mastodon-glitch:latest

EXPOSE 3000

# Set the work dir and the container entry point
WORKDIR /opt/mastodon

# Run the main process
CMD ["bundle" "exec" "rails s -p 3000"]