
- name: create container volumes
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
  with_list:
    - "{{ storage_root }}/{{ namespace }}/redis"
    - "{{ storage_root }}/{{ namespace }}/postgres"
    - "{{ storage_root }}/{{ namespace }}/mastodon"
    - "{{ storage_root }}/{{ namespace }}/public"

- name: create router volumes
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
  with_list:
    - "{{ storage_root }}/router/{{ namespace }}/public"
    - "{{ config_root }}/router"

- name: update all container images
  shell: >
    podman pull {{ artifact_repository }}/{{ base_image }}:{{ base_image_version }}

    podman pull {{ artifact_repository }}/{{ router_image }}:{{ router_image_version }}

    podman pull {{ redis_image }}:{{ redis_image_version }}

    podman pull {{ postgres_image }}:{{ postgres_image_version }}

