

- name: create the database
  shell: >
    podman run -ti --name init \
    --pod {{ namespace }} \
    --env-file={{ config_root }}/.env.prod \
    --env=DISABLE_DATABASE_ENVIRONMENT_CHECK=1 \
    {{ base_image }}:{{ base_image_version }} \
    bundle exec rake db:reset

- name: create a root user for the instance
  shell: >
    podman run -ti --name owner \
    --pod {{ namespace }} \
    --env-file={{ config_root }}/.env.prod \
    {{ base_image }}:{{ base_image_version }} \
    bin/tootctl accounts create ops --email {{ mastodon_owner_mail }} --confirmed --role Owner > /opt/config/master.key

- name: cleanup
  shell: >
    podman rm init owner
