
- name: stop the app
  shell: >
    podman stop sidekiq

    podman stop streaming

    podman stop web


- name: migrate the database
  shell: >
    podman run --name migration \
    --pod {{ pod_namespace }} \
    --env-file={{ config_root }}/.env.prod \
    --env=DISABLE_DATABASE_ENVIRONMENT_CHECK=1 \
    {{ base_image }}:{{ base_image_version }} \
    bundle exec rake db:migrate


- name: start the app
  shell: >
    podman start sidekiq

    podman start streaming

    podman start web


- name: cleanup
  shell: >
    podman rm migration