
- name: create a default static site for LOCAL_DOMAIN
  template:
    src: ../files/index.html
    dest: "{{ storage_root }}/router/{{ namespace }}/public/index.html"
    owner: "{{ svc_user }}"
    group: "{{ svc_user }}"
    mode: "644"
    force: no