name: build-release-containers

on:
  push:
    branches: [main]

env:
  CONTAINER_IMAGE: mastodon
  CONTAINER_VERSION: v4.1.0

  ARTIFACT_REPOSITORY: ${{ secrets.ARTIFACT_REPOSITORY }}
  ARTIFACT_REPOSITORY_HOST: ${{ secrets.ARTIFACT_REPOSITORY_HOST }}

  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout upstream code
        uses: actions/checkout@v3
        with:
          repository: fedimix/mastodon
          ref: release

      - name: checkout deployment artifacts
        uses: actions/checkout@v3
        with:
          repository: txsvc/mastodon-deploy
          path: ".build"
          
      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: authenticate gcloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCLOUD_CREDENTIALS }}"
        id: auth

      - name: setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: authenticate artifact repository
        run: gcloud auth configure-docker $ARTIFACT_REPOSITORY_HOST

      - name: build the base container
        run: |
          docker build --rm=true -t "$CONTAINER_IMAGE":latest -f .build/Dockerfile.base .

      - name: tag and push the container
        run: |
          docker tag "$CONTAINER_IMAGE":latest $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA
          docker tag "$CONTAINER_IMAGE":latest $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
          docker push $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$GITHUB_SHA
          docker push $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
