name: build-latest-containers

on:
  push:
    branches: [develop]

env:
  CONTAINER_IMAGE: mastodon
  CONTAINER_VERSION: latest

  #USERNAME: ${{ secrets.USERNAME }}
  #CR_PAT: ${{ secrets.CR_PAT }}
  ARTIFACT_REPOSITORY: ${{ secrets.ARTIFACT_REPOSITORY }}
  ARTIFACT_REPOSITORY_HOST: ${{ secrets.ARTIFACT_REPOSITORY_HOST }}

  #ARTIFACT_REPOSITORY: fedimix
  #ARTIFACT_REPOSITORY_HOST: ghcr.io

  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_latest:
    runs-on: ubuntu-latest

    steps:
      - name: checkout upstream code
        uses: actions/checkout@v3
        with:
          repository: mastodon/mastodon
          ref: main

      - name: checkout deployment artifacts
        uses: actions/checkout@v3
        with:
          repository: fedimix/mastodon-deploy
          path: ".build"
          
      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: authenticate gcloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCLOUD_CREDENTIALS }}"
        id: auth

      - name: setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: authenticate artifact repository
        run: gcloud auth configure-docker $ARTIFACT_REPOSITORY_HOST
        
      #- name: config ghcr.io
      #  run: |
      #    echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin

      - name: build the base container
        run: |
          docker build --rm=true \
            --build-arg="TARGETPLATFORM=amd64" --build-arg="BUILDPLATFORM=linux/amd64" \
            -t "$CONTAINER_IMAGE":"$CONTAINER_VERSION" -f .build/Dockerfile .

      - name: tag and push the container
        run: |
          docker tag "$CONTAINER_IMAGE":"$CONTAINER_VERSION" $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
          docker push $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
          docker images
          
          