name: build-develop-containers

on:
  push:
    branches: [main]

env:
  CONTAINER_IMAGE: mastodon
  CONTAINER_VERSION: develop
  SOURCE_BASE_VERSION: v4.1.2

  USERNAME: ${{ secrets.USERNAME }}
  CR_PAT: ${{ secrets.CR_PAT }}

  ARTIFACT_REPOSITORY: fedimix
  ARTIFACT_REPOSITORY_HOST: ghcr.io
  
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_develop:
    runs-on: ubuntu-latest

    steps:
      - name: checkout upstream code
        uses: actions/checkout@v3
        with:
          repository: fedimix/mastodon
          ref: develop

      - name: checkout deployment artifacts
        uses: actions/checkout@v3
        with:
          repository: fedimix/mastodon-deploy
          path: ".build"
          
      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: config ghcr.io
        run: |
          echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin

      - name: build the base container
        run: |
          docker build --rm=true -t "$CONTAINER_IMAGE":"$CONTAINER_VERSION" -f .build/Dockerfile.develop .

      - name: tag and push the container
        run: |
          docker tag "$CONTAINER_IMAGE":"$CONTAINER_VERSION" $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
          docker tag "$CONTAINER_IMAGE":"$CONTAINER_VERSION" $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$SOURCE_BASE_VERSION
          docker push $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$CONTAINER_VERSION
          docker push $ARTIFACT_REPOSITORY_HOST/$ARTIFACT_REPOSITORY/$CONTAINER_IMAGE:$SOURCE_BASE_VERSION
          docker images
